export {default as Nav} from './nav'
export {default as Home} from './home'
export {default as Aside} from './aside'
export {default as Diary} from './diary'
export {default as Notice} from './notice'
export {default as Shop} from './shop'
export {default as Login} from './login'
export {default as Register} from './register'